spring:
  application:
    name: microservice-discovery-eureka-ha
  cloud:
    inetutils:
      ignored-interfaces:
        - .*Virtual.*

---

spring:
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    prefer-ip-address: true
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/

---

spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    prefer-ip-address: true
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
