server:
  port: 8761
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: EurekaServer1
  cloud:
    inetutils:
      ignored-interfaces:
        - .*Virtual.*